config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :orders

  resources :products
  root to: 'products#index'

  resources :categories
  root to: 'categories#index'

  resource :cart, only: [:show]

  resources :order_products, only: %i[create update destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :customer do
    get '/sign_in' => 'devise/sessions#new' # custom path to login/sign_in
    get '/sign_up' => 'devise/registrations#new', as: 'new_user_registration' # custom path to sign_up/registration
  end

  devise_for :customers

  resources :customers

  resources :charges

  get '/:name', to: 'pages#show', as: 'page'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories

  belongs_to :parent, class_name: 'Category', optional: true
  has_many :children, class_name: 'Category', foreign_key: 'parent_id'

  validates :name, uniqueness: true, presence: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders

  validates :first_name, :last_name, presence: true

  def after_database_authentication; end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :order_products
  belongs_to :order_status
  belongs_to :customer
  # belongs_to :customer
  # validates :tax, :shipping, :sub_total, :total, presence: true

  before_save :update_subtotal

  def subtotal
    order_products.collect { |op| op.valid? ? (op.qty * op.unit_price) : 0 }.sum
  end

  private

  def update_subtotal
    self[:sub_total] = subtotal
  end
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :total_price, :qty, :unit_price, presence: true
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * qty
  end

  private

  def product_present
    errors.add(:product, 'is not valid or is not active.') if product.nil?
  end

  def order_present
    errors.add(:order, 'is not a valid order.') if order.nil?
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = qty * self[:unit_price]
  end
end

app/models/order_status.rb
# frozen_string_literal: true

class OrderStatus < ApplicationRecord
  has_many :orders

  validates :name, uniqueness: true, presence: true
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  has_one_attached :image
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :order_products
  has_many :product_categories
  has_many :categories, through: :product_categories

  has_one_attached :image

  validates :title, :price, :ingredient_list, presence: true

  paginates_per 30
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category

  validates :product_name, :qty, presence: true
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @order_products = current_order.order_products
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def show
    @page = Page.find_by_page_name(params[:name])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/charges_helper.rb
# frozen_string_literal: true

module ChargesHelper
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/admin/pages/_form.html.haml
= semantic_form_for [:admin, @page], builder: ActiveAdmin::FormBuilder do |f|
  = f.inputs do
    = f.input :body
    = f.input :sub_content
    = f.input :header
    = f.input :page_name
    = f.input :image, as: :file
    = f.actions

app/views/shared/_footer.html.erb

    <div class="container">
        <div class="columns">
          <div class="column is-fullwidth footer-sub-content has-text-centered">
            <%= link_to root_path do %>
              <%= image_tag(image_url("logo.png"),alt: 'logo') %>
            <% end %>
        </div>
    </div>
    <div class="is-divider"></div>
    <div class="columns">
            <div class="column">
                <div class="content">
                    <h3>Follow me</h3>
                    <a class="button is-medium" target="_blank" href="https://github.com/GhileMear/Beyondfresh_ecommerce">
                        <span class="icon is-medium">
                            <i class="fab fa-github"></i>
                        </span>
                        <span>GitHub</span>
                    </a>
                </div>
            </div>
            <div class="column">
                <div class="content">
                    <h3>More Information</h3>
                    <% Page.all.each do |page|%>
                        <%= link_to page.page_name, page_path(name: page.page_name) %>
                    <% end %>
                </div>
            </div>
        </div>
</div >

app/views/shared/_function_menu.html.erb

<nav class="navbar" aria-label="main navigation">
  <div class="navbar-menu is-active">
    <div class="navbar-brand">
      <%= link_to root_path do %>
        <%= image_tag(image_url("logo.png"),alt: 'logo') %>
      <% end %>
      </div>
    <div class="navbar-start">
        <div class="navbar-item search-bar-width">
          <%= form_tag(products_path,method: :get, class: "search-bar-width") do %>
            <div class="field is-horizontal search-bar-width has-addons">
              <div class="control">
              <div class="select is-medium">
                <%= select_tag :category_search, options_from_collection_for_select(Category.where(is_main_category: true), "id", "name"),prompt: "All", class: "is-medium"%>
              </div>
              </div>
              <div class="control search-bar-width">
                <%= text_field_tag :search,"", class: "input is-medium search-bar-width", placeholder: "Search..." %>
              </div>
              <div class="control is-fullwidth">
                <%= button_tag(type: "submit", class: "button is-medium") do %>
                  <i class="fa fa-search"></i>
                <% end %>
              </div>
            </div>
          <% end %>
      </div>
    </div>
    <div class="navbar-end cart-text">
      <%= render 'layouts/cart_progress' %>
    </div>
  </div>
</nav>
<nav
      class="navbar secondary-menu"
    >
      <div
        class="navbar-burger burger"
        role="button"
        aria-label="menu"
        aria-expanded="false"
        data-target="navbar"
      >
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </div>

      <div
        id="navbar"
        class="navbar-menu"
      >
        <div class="navbar-start">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link margin-medium'">Products</a>
            <div class="navbar-dropdown">
              <% Category.where(is_main_category: true).each do |category| %>
                <%= link_to category.name, category, class: "navbar-item is-hoverable" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
            <% if current_customer.nil? %>
              <a
                class="button is-primary"
                href="/sign_up"
              >
              <strong>Sign up</strong>
              </a>
              <a
                class="button is-light"
                href="/sign_in"
              >Log in</a>
            <% else %>
              <%= link_to "#{current_customer.first_name}'s Corner",current_customer, class: "button is-primary" %>
              <%= link_to "Sign Out", destroy_customer_session_path, method: :delete, class: "button is-light" %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
</nav>